import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { PokemonProvider } from "./context/PokemonContext";
import { ClientProviders } from "./context/ClientProvider";

import ThemeRegistry from "./theme/ThemeRegistry";
import "./globals.css";
import { CssBaseline } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ClientProviders>
          <ThemeRegistry>
            <CssBaseline />
            {children}
            </ThemeRegistry>
        </ClientProviders>
      </body>
    </html>
  );
}
